---
- src: https://github.com/blaisep/ansible-ntp.git
- src: https://github.com/blaisep/ansible-opennms.git
- src: https://github.com/blaisep/ansible-oracle-java8.git
- src: https://github.com/blaisep/ansible-postfix.git
- src: https://github.com/blaisep/ansible-postgresql.git
