---
- name: debian | installing python and git
  apt:
    name:
        - git
        - python python-pip
        - python-dev
  state: "present"
  become: true

- name: debian | installing pip
  pip:
    name:
        - ansible
        - jinja2
        - setuptools
    state: "present"

- name: debian | adding opennms repo key
  apt_key:
    url: https://debian.opennms.org/OPENNMS-GPG-KEY
    state: present

- name: debian | adding opennms repo to sources list
  apt_repository:
    repo: deb http://debian.opennms.org stable main
    state: present

- name: debian | adding opennms source repo to sources list
  apt_repository:
    repo: deb-src http://debian.opennms.org stable main
    state: present

- name: debian | installing opennms
  apt:
    name: "opennms"
    state: present